[general]
log_level = true
base_topic = true
cache_size = true

[broker]
host = true
port = true
user = true
password = true
client_id = true

[miniserver]
miniserver_ip = true
miniserver_port = true
miniserver_user = true
miniserver_pass = true
sync_with_miniserver = true

[topics]
subscriptions = true
subscription_filters = true
topic_whitelist = true
do_not_forward = true

[processing]
expand_json = true
convert_booleans = true

[udp]
udp_in_port = true
udp_source_filter_enabled = true
udp_allowed_sources = true
